/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ArtistRef: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        /** @enum {string} */
        EventStatus: "onsale" | "offsale" | "cancelled" | "rescheduled" | "postponed";
        /** @enum {string} */
        Platform: "biletix" | "passo" | "bubilet" | "biletinial";
        VenueRef: {
            /** Format: uuid */
            id: string;
            name: string;
            city: string;
            /** @description ISO 3166-1 alpha-2, ex. TR */
            countryCode: string;
        };
        EventSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            status: components["schemas"]["EventStatus"];
            /** Format: date-time */
            startsAt: string;
            /** Format: date */
            localDate: string;
            localTime: string | null;
            timezone: string;
            venue: components["schemas"]["VenueRef"];
            artists: components["schemas"]["ArtistRef"][];
            platforms: components["schemas"]["Platform"][];
            /** Format: uri */
            imageUrl: string | null;
            priceMin: number | null;
            priceMax: number | null;
            currency: string | null;
        };
        PageMeta: {
            /** @description 1'den başlar (ilk sayfa = 1) */
            page: number;
            size: number;
            /** Format: int64 */
            totalElements: number;
        };
        EventPage: components["schemas"]["PageMeta"] & {
            items: components["schemas"]["EventSummary"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
